// <auto-generated />
namespace Exam_MusicalShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class thirdMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(thirdMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202003311721409_thirdMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
